# API
spring.application.name=VidexiumService
app.version=@project.version@

# POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_videxium_desenvolvimento
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop

# CONFIGURACAO
jwt.secret=br.com.videxium.videxiumapi.videxium.service
