# API
spring.application.name=VidexiumService
app.version=@project.version@

# POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_videxium_desenvolvimento
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

# JWT
jwt.secret=eyJhbGciOiJIUzI1NiJs.eyJyb2xlIjoiQURNSU5JU1RSQURPUiIsInN1YiI6InNuYnVpcXJxeXNwcWV3dmt1aEBuZsNvcGYuY29tIiwiaWF0IjoxNzY2MDY0NDM0LCJleHAiOjE3Njg2NTY0MzR9.wQ-SJoZt4b9sxTwX4z8-nAjBYay6AbPE8e092MRnkX4

# FLYWAY
spring.flyway.enabled=true

# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=repository.desenvolvimento@gmail.com
spring.mail.password=ittd bwhj iiob terk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true